'use client';

import Head from "next/head"
import "@/styles/global.css"
import { useState } from "react";
import AppContext from "@/contexts/AppContext";
import { Box, ThemeProvider } from "@mui/material";
import { theme } from "@/themes/theme";
import { Lato } from 'next/font/google'
import { SnackbarProvider } from "notistack";

const lato = Lato({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', "400", "700", "900"]
})

const DefaultLayout = ({ children }: any) => {

  const [auth, setAuth] = useState({})

  const contextValues = { auth: { auth, setAuth } }

  return (
    <html className={lato.className}>
      <Head>
        <title>BiteBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <body>
        <main>
          <AppContext.Provider value={contextValues}>
            <ThemeProvider theme={theme}>
              <SnackbarProvider
                anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                autoHideDuration={3000}
                maxSnack={2}
              >
                <Box
                  style={{
                    backgroundColor: theme.palette.background.default,
                    minHeight: '100svh'
                  }}
                >
                  {children}
                </Box>
              </SnackbarProvider>
            </ThemeProvider>
          </AppContext.Provider>
        </main>
      </body>
    </html>
  )
}

export default DefaultLayout